# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-28 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitdecisionApi', '0002_group_groupmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('amount', models.IntegerField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_items', to='splitdecisionApi.Group')),
            ],
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='splitdecisionApi.Group'),
        ),
    ]
