# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-03 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitdecisionApi', '0004_debtobligation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtobligation',
            name='debt_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_obligations', to='splitdecisionApi.DebtItem'),
        ),
    ]
